version: '3'
services:
  ghost:
    image: ghost:1-alpine
    ports:
      - 2368:2368
    environment:
      database_client: mysql
      database__connection__database: ghost
      database__connection__host: db
      database__connection__user: user
      database__connection__password: password
    depends_on:
      - "db"
    networks:
      - my-network
  
  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/
    networks:
      - my-network
    environment:
      - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
volumes:
  db:

networks:
  my-network: